export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const SET_ACTIVITIES = 'SET_ACTIVITIES';

export const SET_LAST_FINISHED = 'SET_LAST_FINISHED';
export const GET_LAST_FINISHED = 'GET_LAST_FINISHED';
