export const SET_ITEM_TO_BE_PLAYED = 'SET_ITEM_TO_BE_PLAYED';
export const SET_BACK_TO_SCREEN = 'SET_BACK_TO_SCREEN';
export const SET_CURRENT_AUDIO = 'SET_CURRENT_AUDIO';
export const SET_JUMP_TO_SONG = 'SET_JUMP_TO_SONG';
export const SET_WAS_PLAYING = 'SET_WAS_PLAYING';
