export const CATEGORIES_SET = 'CATEGORIES_SET';
export const CATEGORIES_GET = 'CATEGORIES_GET';

export const CATEGORIES_ITEMS_GET = 'CATEGORIES_ITEMS_GET';
export const CATEGORIES_ITEMS_SET = 'CATEGORIES_ITEMS_SET';
export const CATEGORIES_ITEMS_LOAD_MORE = 'CATEGORIES_ITEMS_LOAD_MORE';
export const CATEGORIES_ITEMS_APPEND = 'CATEGORIES_ITEMS_APPEND';
export const RESET_CATEGORY_ITEMS = 'RESET_CATEGORY_ITEMS';

export const ACTIVE_CATEGORY_ITEM_SET = 'ACTIVE_CATEGORY_ITEM_SET';
export const ACTIVE_CATEGORY_ITEM_GET = 'ACTIVE_CATEGORY_ITEM_GET';

export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const SET_CATEGORY_LOADING = 'SET_CATEGORY_LOADING';

export const RESET_CATEGORY_ITEMS_PAGINATION = 'RESET_CATEGORY_ITEMS_PAGINATION';

export const GET_CATEGORY_TABS = 'GET_CATEGORY_TABS';
export const SET_CATEGORY_TABS = 'SET_CATEGORY_TABS';

export const CLEAR_CATEGORY_TABS = 'CLEAR_CATEGORY_TABS';
