export const LIBRARY_ITEMS_GET = 'LIBRARY_ITEMS_GET';
export const LIBRARY_ITEMS_SET = 'LIBRARY_ITEMS_SET';
export const LIBRARY_ITEMS_LOAD_MORE = 'LIBRARY_ITEMS_LOAD_MORE';
export const LIBRARY_ITEMS_APPEND = 'LIBRARY_ITEMS_APPEND';

export const ACTIVE_LIBRARY_ITEM_SET = 'ACTIVE_LIBRARY_ITEM_SET';
export const ACTIVE_LIBRARY_ITEM_GET = 'ACTIVE_LIBRARY_ITEM_GET';

export const GET_LIBRARY_TABS = 'GET_LIBRARY_TABS';
export const SET_LIBRARY_TABS = 'SET_LIBRARY_TABS';
