export const MEDITATIONS_GET = 'MEDITATIONS_GET';
export const MEDITATIONS_SET = 'MEDITATIONS_SET';
export const MEDITATIONS_APPEND = 'MEDITATIONS_APPEND';
export const MEDITATIONS_LOAD_MORE = 'MEDITATIONS_LOAD_MORE';

export const ACTIVE_MEDITATION_SET = 'ACTIVE_MEDITATION_SET';
export const ACTIVE_MEDITATION_GET = 'ACTIVE_MEDITATION_GET';

export const GET_MEDITATION_TABS = 'GET_MEDITATION_TABS';
export const SET_MEDITATION_TABS = 'SET_MEDITATION_TABS';
