export const INIT_PURCHASES = 'INIT_PURCHASES';

export const REQUEST_SUBSCRIPTION = 'REQUEST_SUBSCRIPTION';

export const RESTORE_PURCHASES = 'RESTORE_PURCHASES';

export const SET_PURCHASES_INITIALIZED = 'SET_PURCHASES_INITIALIZED';
