export const GET_SCENES = 'GET_SCENES';
export const SET_SCENES = 'SET_SCENES';
export const SET_ACTIVE_SCENE = 'SET_ACTIVE_SCENE';
export const SET_SCENE_PREVIEW = 'SET_SCENE_PREVIEW';
export const SET_SCENE_MODAL_VISIBLE = 'SET_SCENE_MODAL_VISIBLE';
export const SET_SCENE_FOCUSED = 'SET_SCENE_FOCUSED';
