export const SHOP_ITEMS_GET = 'SHOP_ITEMS_GET';
export const SHOP_ITEMS_SET = 'SHOP_ITEMS_SET';
export const SHOP_ITEMS_APPEND = 'SHOP_ITEMS_APPEND';
export const SHOP_ITEMS_LOAD_MORE = 'SHOP_ITEMS_LOAD_MORE';
